files:
  - source: /packages/plant-playground/public/locales/en-US/*.json
    translation: /packages/plant-playground/public/locales/%locale%/%original_file_name%
  - source: /packages/documentation/en-US/docs/**/*.md
    ignore:
      - /packages/documentation/en-US/docs/reference/**/*
    translation: /packages/documentation/%locale%/docs/**/%original_file_name%
