copyright: Oliver Salzburg
dev_addr: 0.0.0.0:8000
docs_dir: docs
edit_uri: /oliversalzburg/plantdb/edit/main/packages/documentation/docs/
extra:
  alternate:
    - name: English (US)
      link: /plantdb/docs/en-US/
      lang: en
    - name: Deutsch (DE)
      link: /plantdb/docs/de-DE/
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oliversalzburg/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: blockdiag
          class: blockdiag
          format: !!python/name:blockdiag_fences.blockdiag.fence_img_format
        - name: seqdiag
          class: seqdiag
          format: !!python/name:blockdiag_fences.blockdiag.fence_img_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - search
repo_name: oliversalzburg/plantdb
repo_url: https://github.com/oliversalzburg/plantdb/
site_name: PlantDB
site_url: https://github.com/oliversalzburg/plantdb/docs/
theme:
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: material/flower
    repo: fontawesome/brands/github
  language: de
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: teal
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light green
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
