name: QA

on:
  pull_request:
  push:

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      # Pre-build QA
      - name: Check constraints
        run: yarn constraints

      # Build
      - name: Build
        run: |
          yarn workspace @plantdb/libplantdb build
          yarn workspace @plantdb/plant-cli build
          yarn workspace @plantdb/plant-nursery build

      # Post-build QA
      - name: Lint Prettier
        run: yarn lint:prettier
      - name: Lint ESLint
        run: yarn lint:eslint
      - name: Lint TSC
        run: yarn lint:tsc
